import Head from 'next/head';
import { HeroBanner, Products } from '../components';
import FooterBanner from '../components/FooterBanner';
import { client } from '../lib/client';


export default function Home({productsData,bannerData}) {
  // console.log(productsData)
  // console.log(bannerData)
  return (
    <div className="relative bg-white h-full ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     

     
      <div className="relative mt-28">
        <HeroBanner bannerData={bannerData?.length && bannerData[0]} />

        <div className="text-center mt-10">
          <h1 className="text-4xl font-extrabold lg:font-black text-center text-[#1e3932]">Best Selling Products</h1>
          <p className="text-black font-semibold">Speakers of many variations</p>
        </div>
      </div>
     <Products productsData={productsData} />

     <FooterBanner bannerData={bannerData?.length && bannerData[0]}/>
    </div>
  )
}

export const getServerSideProps = async () => {
  const productsQuery = (`*[_type == "product"]`);
  const productsData = await client.fetch(productsQuery);
  const bannerQuery = (`*[_type == "banner"]`);
  const bannerData = await client.fetch(bannerQuery);

  return {
    props: {
      productsData,
      bannerData
    }
  }
}